kind: AIchorManifest
apiVersion: 0.2.2

builder:
  image: image
  context: smoke-test # smoke-test folder
  dockerfile: ./build/ray.Dockerfile # need ray installed

spec:
  operator: kuberay
  image: image
  command: "python3 -u main.py --operator=kuberay --sleep=300 --tb-write=True"

  engineName: aws-engine

  debug:
    jupyter: false

  tensorboard:
    enabled: true

  types:
    Head:
      resources:
        cpus: 6
        ramRatio: 6
        accelerators: # optional
          gpu:
            count: 1
            product: a10g
            type: gpu

    Workers:
      - name: cpu-workers
        count: 1
        resources:
          cpus: 1
          ramRatio: 2
          shmSizeGB: 0
